	CONTROL_SCHEME_PS2 = 1
	CONTROL_SCHEME_XBOX = 2
	LAUNCHER_RESOLUTION_WIDESCREEN = 0
    
	UNDERGROUNDPLUS_DEBUG = 0
	UNDERGROUNDPLUS_DEVBUILD = 1
	UNDERGROUNDPLUS_CONTROLS = CONTROL_SCHEME_XBOX
	
	
	
	
	
