    // Underground+ option values/text
	CONTROL_SCHEME_PS2 = 1
	CONTROL_SCHEME_XBOX = 2
	UNDERGROUNDPLUS_OPTION_OFF = "Off"
	UNDERGROUNDPLUS_OPTION_ON = "On"
    
	LAUNCHER_RESOLUTION_WIDESCREEN = 0 // This is set by the launcher
    
	UNDERGROUNDPLUS_DEBUG = 0
	UNDERGROUNDPLUS_DEVBUILD = 0
	UNDERGROUNDPLUS_CONTROLS = CONTROL_SCHEME_XBOX
    UNDERGROUNDPLUS_ENABLE_EXITBOARD = UNDERGROUNDPLUS_OPTION_ON
	//UNDERGROUNDPLUS_GFX_QUALITY = 0 - now set in launcher.qb
	
	
	
	
